name: Canary
on:
  schedule:
    - cron: 0 3 * * *
jobs:
  canary:
    name: Canary ${{ matrix.runtime }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        runtime: [deno, node, bun]
    env:
      RUST_BACKTRACE: full
      DENO_FUTURE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Setup Node
        if: ${{ matrix.runtime == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: nightly
        run: corepack enable

      - name: Setup Bun
        if: ${{ matrix.runtime == 'bun' }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Enable corepack
        run: command -v corepack >/dev/null 2>&1 && corepack enable

      - name: Install deps
        run: deno task setup:${{ matrix.runtime }}

      - name: Run tests
        run: deno task test:${{ matrix.runtime }}
